### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by chyhaiyang** [vision4robotics/SiameseTracking4UAV#7]
请问可以提供数据集的下载方式吗？我这边发现提供的代码处理不了官方的数据集，例如UAV@12310FPS

**Comment by L-KH97** [comment]
Thanks for your question
For the convenience of using the datasets, we have made adjustments and no longer need to use json files. You can refer to the usage in "/snot/datasets/__init__.py", for example, enter "UAV10" at "--dataset" to use UAV@12310FPS. Alternatively, you can also find official links at the introduction of the relevant datasets on the homepage.

感谢您的问题
为方便使用数据集，我们做了调整，不再需要json文件来使用，您可以参考"/snot/datasets/__init__.py"内的使用方式，例如，在"--dataset"处输入"UAV10"以使用UAV@12310FPS。或者，您也可以在首页相关数据集的介绍处找到官方的链接。
